### ISSUE TITLE
Acoustic data

### ISSUE THREAD

**Issue by ziqihuang233** [TristanLouthRobins/Wrangling_In_The-Antipodes#3]
Can you share some sample of orginal acoustic data (e.g. wav file)?

**Comment by TristanLouthRobins** [comment]
With reference to any particular R script in the repository - i.e. WITA11 (monitoR), WITA12 (lady bay reef EDA)?

**Comment by ziqihuang233** [comment]
I saw the data set in the data folder. However, I am more curious about the raw data, which like the audible recording you posted in your blog. Unfortunately, I cannot download the aduio in the blog. So could you share some samples here?

**Comment by TristanLouthRobins** [comment]
Ok, thanks for clarifying! Which blog post was it though? If you can let me know I'll have a better idea of the acoustic data that I can provide samples of.

**Comment by ziqihuang233** [comment]
I am really interested in about this. The link is https://wranglingintheantipodes.wordpress.com/2022/12/19/acoustic-complexity-as-an-indicator-of-tidal-activity/. Thank you.

**Comment by TristanLouthRobins** [comment]
Hi Crystal, no problem and thank you for your interest! I'm now in the process of uploading some audio samples in .wav format. My internet upload speed is quite slow at the moment so it may take awhile for the folder to upload. I've included the audio files for the periods of 5pm to 6pm (high tide), 11pm to 12am (low tide) and 2am to 3am (transitional tide) over the period of observation - 10am 8th Oct 22 to 9th Oct 22 12pm.

**Comment by TristanLouthRobins** [comment]
The folder will be located under this directory once uploaded: https://github.com/TristanLouthRobins/Wrangling_In_The-Antipodes/tree/main/data

**Comment by TristanLouthRobins** [comment]
Should you decide to use any of the raw data and/or legacy code for published research purposes, if you could attribute it to me that would be much appreciated. I am currently working on a new post for the blog which expands on this previous research. It was done back in December 2022 on the reef and spans an entire week with two AudioMoths deployed. I am trying to get the post done this month, but finding the time is tricky. Hopefully I'll have it done by April and will have the data/outputs pushed to this repository. Thanks once again for your interest. Warm Regards, Tristan

**Comment by ziqihuang233** [comment]
Thank you for your sharing!!!
